---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: apilon-namespace
spec:
  selector:
    matchLabels:
      app: mysql # Attention à bien avoir les mêmes dans la template de pod
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: admin
        - name: MYSQL_DATABASE
          value: wordpress
        - name: MYSQL_PASSWORD
          value: wordpress
        - name: MYSQL_USER
          value: wordpress