---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: apilon-namespace
spec:
  selector:
    matchLabels:
      app: mysql # Attention à bien avoir les mêmes dans la template de pod
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: admin
        - name: MYSQL_DATABASE
          value: wordpress
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql-password
        - name: MYSQL_USER
          value: wordpress
        volumeMounts:
        - name: mysql-data
          mountPath: /var/lib/mysql
        - name: mysql-secret
          mountPath: "/mnt/secrets-store"
          readOnly: true
      volumes:
      - name: mysql-data
        persistentVolumeClaim:
          claimName: mysql-pvc
      - name: mysql-secret
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: "wordpress-spc"
    