---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  namespace: apilon-namespace
spec:
  selector:
    matchLabels:
      app: wordpress # Attention à bien avoir les mêmes dans la template de pod
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        image: testregistryapilon.azurecr.io/wordpress:v1
        env:
        - name: WORDPRESS_DB_HOST
          value: mysql
        - name: WORDPRESS_DB_USER
          value: wordpress
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql-password
        - name: WORDPRESS_DB_NAME
          value: wordpress
        volumeMounts:
        - name: wordpress-data
          mountPath: /var/www/html
        resources:
          requests:
            cpu: 50m
      volumes:
      - name: wordpress-data
        persistentVolumeClaim:
          claimName: wordpress-pvc